"""add questionnaire jobs and responses

Revision ID: df152d8f600c
Revises: a1b2c3d4e5f6
Create Date: 2026-04-25 17:42:26.760285

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'df152d8f600c'
down_revision: Union[str, Sequence[str], None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('questionnaire_jobs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('result', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('questionnaire_responses',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('questionnaire_job_id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('question_idx', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('resposta', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['questionnaire_job_id'], ['questionnaire_jobs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('questionnaire_job_id', 'question_idx', 'user_id', name='uq_questionnaire_response')
    )
    op.alter_column('projects', 'status',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Enum('rascunho', 'em_analise', 'submetido', 'aprovado', name='projectstatusenum', native_enum=False),
               existing_nullable=False,
               existing_server_default=sa.text("'rascunho'::character varying"))
    op.alter_column('projects', 'departamento',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Enum('FCTE', 'FGA', 'FACE', 'FACE_GPP', 'FACE_ADM', 'FACE_CCA', 'FACE_ECO', 'FACE_CIORD', 'FACE_CEIGES', 'FCTS', 'FCE', 'FAU', 'FAU_PRO', 'FAU_TEC', 'FAU_THAU', 'FAU_CPAB', 'FAV', 'FAC', 'FAC_DAP', 'FAC_JOR', 'FAC_COM', 'FCI', 'FD', 'FE', 'FE_MTC', 'FE_PGE', 'FE_TEF', 'FEF', 'FEF_CO', 'FUP', 'FM', 'FS', 'FS_FAR', 'FS_ODT', 'FS_DSC', 'FS_ENF', 'FS_NUT', 'FT', 'FT_EPR', 'FT_EFL', 'FT_ENC', 'FT_ENE', 'FT_ENM', 'FT_CEFTRU', 'IB', 'IB_BOT', 'IB_CEL', 'IB_CFS', 'IB_ECL', 'IB_FIT', 'IB_GEM', 'IB_ZOO', 'IB_CNANO', 'IB_CP', 'ICS', 'ICS_ELA', 'ICS_DAN', 'ICS_SOL', 'IDA', 'IDA_CEN', 'IDA_DIN', 'IDA_MUS', 'IDA_VIS', 'IE', 'IE_CIC', 'IE_EST', 'IE_MAT', 'IF', 'IF_CIF', 'IG', 'IG_SIS', 'ICH', 'ICH_FIL', 'ICH_GEA', 'ICH_HIS', 'ICH_SER', 'IL', 'IL_LET', 'IL_LIP', 'IL_TEL', 'IP', 'IP_PST', 'IP_PCL', 'IP_PED', 'IP_PPB', 'IP_CAEP', 'IPOL', 'IQ', 'IREL', name='departamentoenum', native_enum=False),
               existing_nullable=True)
    op.alter_column('projects', 'area_primaria',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Enum('EXATAS', 'BIOLOGICAS', 'ENGENHARIAS', 'SAUDE', 'AGRARIAS', 'SOCIAIS_APLIC', 'HUMANAS', 'OUTRA', name='areacnpqenum', native_enum=False),
               existing_nullable=True)
    op.alter_column('projects', 'subarea_primaria',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Enum('MAT', 'PROB_EST', 'COMP', 'ASTRO', 'FIS', 'QUIM', 'GEO', 'OCEAN', 'BIO_GERAL', 'GENET', 'BOT_B', 'ZOO_B', 'ECOL', 'MORF', 'FISIOL', 'BIOQUIM', 'BIOFIS', 'FARMACOL', 'IMUNOL', 'MICROBIOL', 'PARASITOL', 'BIOL_MOL', 'ENG_CIV', 'ENG_MIN', 'ENG_MAT', 'ENG_ELE', 'ENG_MEC', 'ENG_QUIM', 'ENG_SAN', 'ENG_PROD', 'ENG_NUC', 'ENG_TRANSP', 'ENG_NAV', 'ENG_AERO', 'ENG_BIOMED', 'MED', 'ODONT', 'FARM', 'ENFERM', 'NUTRI', 'SAUDE_COL', 'FONOA', 'FISIOTER', 'ED_FIS', 'AGRON', 'REC_FLOR', 'ENG_AGRIC', 'ZOOTEC', 'MED_VET', 'REC_PESC', 'CI_ALIM', 'DIR', 'ADM_S', 'ECON_S', 'ARQ_URB', 'PLAN_URB', 'COMUN', 'CI_INF', 'MUSEOL', 'SERV_SOC', 'ECON_DOM', 'DES_IND', 'TURISMO', 'FILOS', 'SOCIOL', 'ANTROP', 'ARQUEOL', 'HIST', 'GEOGR', 'PSICOL', 'EDUC', 'CI_POL', 'TEOL', 'LING', 'LIT', 'ARTES', 'OUTRA_SUB', name='subareacnpqenum', native_enum=False),
               existing_nullable=True)
    op.alter_column('projects', 'area_secundaria',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Enum('EXATAS', 'BIOLOGICAS', 'ENGENHARIAS', 'SAUDE', 'AGRARIAS', 'SOCIAIS_APLIC', 'HUMANAS', 'OUTRA', name='areacnpqenum', native_enum=False),
               existing_nullable=True)
    op.alter_column('projects', 'subarea_secundaria',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Enum('MAT', 'PROB_EST', 'COMP', 'ASTRO', 'FIS', 'QUIM', 'GEO', 'OCEAN', 'BIO_GERAL', 'GENET', 'BOT_B', 'ZOO_B', 'ECOL', 'MORF', 'FISIOL', 'BIOQUIM', 'BIOFIS', 'FARMACOL', 'IMUNOL', 'MICROBIOL', 'PARASITOL', 'BIOL_MOL', 'ENG_CIV', 'ENG_MIN', 'ENG_MAT', 'ENG_ELE', 'ENG_MEC', 'ENG_QUIM', 'ENG_SAN', 'ENG_PROD', 'ENG_NUC', 'ENG_TRANSP', 'ENG_NAV', 'ENG_AERO', 'ENG_BIOMED', 'MED', 'ODONT', 'FARM', 'ENFERM', 'NUTRI', 'SAUDE_COL', 'FONOA', 'FISIOTER', 'ED_FIS', 'AGRON', 'REC_FLOR', 'ENG_AGRIC', 'ZOOTEC', 'MED_VET', 'REC_PESC', 'CI_ALIM', 'DIR', 'ADM_S', 'ECON_S', 'ARQ_URB', 'PLAN_URB', 'COMUN', 'CI_INF', 'MUSEOL', 'SERV_SOC', 'ECON_DOM', 'DES_IND', 'TURISMO', 'FILOS', 'SOCIOL', 'ANTROP', 'ARQUEOL', 'HIST', 'GEOGR', 'PSICOL', 'EDUC', 'CI_POL', 'TEOL', 'LING', 'LIT', 'ARTES', 'OUTRA_SUB', name='subareacnpqenum', native_enum=False),
               existing_nullable=True)
    op.alter_column('users', 'privilegio',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Enum('admin', 'usuario', 'avaliador', name='privilegioenum', native_enum=False),
               existing_nullable=False,
               existing_server_default=sa.text("'usuario'::character varying"))
    op.alter_column('users', 'titulo',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Enum('MEST', 'DOUT', 'PDOC', 'PROF_EF', 'PROF_VIS', 'PROF_SUB', 'PG_MEST', 'PG_DOUT', 'PESQ_VOL', 'ESPEC', 'EMER', 'OUTRO', name='tituloenum', native_enum=False),
               existing_nullable=True)
    op.alter_column('users', 'departamento',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Enum('FCTE', 'FGA', 'FACE', 'FACE_GPP', 'FACE_ADM', 'FACE_CCA', 'FACE_ECO', 'FACE_CIORD', 'FACE_CEIGES', 'FCTS', 'FCE', 'FAU', 'FAU_PRO', 'FAU_TEC', 'FAU_THAU', 'FAU_CPAB', 'FAV', 'FAC', 'FAC_DAP', 'FAC_JOR', 'FAC_COM', 'FCI', 'FD', 'FE', 'FE_MTC', 'FE_PGE', 'FE_TEF', 'FEF', 'FEF_CO', 'FUP', 'FM', 'FS', 'FS_FAR', 'FS_ODT', 'FS_DSC', 'FS_ENF', 'FS_NUT', 'FT', 'FT_EPR', 'FT_EFL', 'FT_ENC', 'FT_ENE', 'FT_ENM', 'FT_CEFTRU', 'IB', 'IB_BOT', 'IB_CEL', 'IB_CFS', 'IB_ECL', 'IB_FIT', 'IB_GEM', 'IB_ZOO', 'IB_CNANO', 'IB_CP', 'ICS', 'ICS_ELA', 'ICS_DAN', 'ICS_SOL', 'IDA', 'IDA_CEN', 'IDA_DIN', 'IDA_MUS', 'IDA_VIS', 'IE', 'IE_CIC', 'IE_EST', 'IE_MAT', 'IF', 'IF_CIF', 'IG', 'IG_SIS', 'ICH', 'ICH_FIL', 'ICH_GEA', 'ICH_HIS', 'ICH_SER', 'IL', 'IL_LET', 'IL_LIP', 'IL_TEL', 'IP', 'IP_PST', 'IP_PCL', 'IP_PED', 'IP_PPB', 'IP_CAEP', 'IPOL', 'IQ', 'IREL', name='departamentoenum', native_enum=False),
               existing_nullable=True)
    op.drop_constraint(op.f('uq_users_email'), 'users', type_='unique')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=False)
    op.create_unique_constraint(op.f('uq_users_email'), 'users', ['email'], postgresql_nulls_not_distinct=False)
    op.alter_column('users', 'departamento',
               existing_type=sa.Enum('FCTE', 'FGA', 'FACE', 'FACE_GPP', 'FACE_ADM', 'FACE_CCA', 'FACE_ECO', 'FACE_CIORD', 'FACE_CEIGES', 'FCTS', 'FCE', 'FAU', 'FAU_PRO', 'FAU_TEC', 'FAU_THAU', 'FAU_CPAB', 'FAV', 'FAC', 'FAC_DAP', 'FAC_JOR', 'FAC_COM', 'FCI', 'FD', 'FE', 'FE_MTC', 'FE_PGE', 'FE_TEF', 'FEF', 'FEF_CO', 'FUP', 'FM', 'FS', 'FS_FAR', 'FS_ODT', 'FS_DSC', 'FS_ENF', 'FS_NUT', 'FT', 'FT_EPR', 'FT_EFL', 'FT_ENC', 'FT_ENE', 'FT_ENM', 'FT_CEFTRU', 'IB', 'IB_BOT', 'IB_CEL', 'IB_CFS', 'IB_ECL', 'IB_FIT', 'IB_GEM', 'IB_ZOO', 'IB_CNANO', 'IB_CP', 'ICS', 'ICS_ELA', 'ICS_DAN', 'ICS_SOL', 'IDA', 'IDA_CEN', 'IDA_DIN', 'IDA_MUS', 'IDA_VIS', 'IE', 'IE_CIC', 'IE_EST', 'IE_MAT', 'IF', 'IF_CIF', 'IG', 'IG_SIS', 'ICH', 'ICH_FIL', 'ICH_GEA', 'ICH_HIS', 'ICH_SER', 'IL', 'IL_LET', 'IL_LIP', 'IL_TEL', 'IP', 'IP_PST', 'IP_PCL', 'IP_PED', 'IP_PPB', 'IP_CAEP', 'IPOL', 'IQ', 'IREL', name='departamentoenum', native_enum=False),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)
    op.alter_column('users', 'titulo',
               existing_type=sa.Enum('MEST', 'DOUT', 'PDOC', 'PROF_EF', 'PROF_VIS', 'PROF_SUB', 'PG_MEST', 'PG_DOUT', 'PESQ_VOL', 'ESPEC', 'EMER', 'OUTRO', name='tituloenum', native_enum=False),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)
    op.alter_column('users', 'privilegio',
               existing_type=sa.Enum('admin', 'usuario', 'avaliador', name='privilegioenum', native_enum=False),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False,
               existing_server_default=sa.text("'usuario'::character varying"))
    op.alter_column('projects', 'subarea_secundaria',
               existing_type=sa.Enum('MAT', 'PROB_EST', 'COMP', 'ASTRO', 'FIS', 'QUIM', 'GEO', 'OCEAN', 'BIO_GERAL', 'GENET', 'BOT_B', 'ZOO_B', 'ECOL', 'MORF', 'FISIOL', 'BIOQUIM', 'BIOFIS', 'FARMACOL', 'IMUNOL', 'MICROBIOL', 'PARASITOL', 'BIOL_MOL', 'ENG_CIV', 'ENG_MIN', 'ENG_MAT', 'ENG_ELE', 'ENG_MEC', 'ENG_QUIM', 'ENG_SAN', 'ENG_PROD', 'ENG_NUC', 'ENG_TRANSP', 'ENG_NAV', 'ENG_AERO', 'ENG_BIOMED', 'MED', 'ODONT', 'FARM', 'ENFERM', 'NUTRI', 'SAUDE_COL', 'FONOA', 'FISIOTER', 'ED_FIS', 'AGRON', 'REC_FLOR', 'ENG_AGRIC', 'ZOOTEC', 'MED_VET', 'REC_PESC', 'CI_ALIM', 'DIR', 'ADM_S', 'ECON_S', 'ARQ_URB', 'PLAN_URB', 'COMUN', 'CI_INF', 'MUSEOL', 'SERV_SOC', 'ECON_DOM', 'DES_IND', 'TURISMO', 'FILOS', 'SOCIOL', 'ANTROP', 'ARQUEOL', 'HIST', 'GEOGR', 'PSICOL', 'EDUC', 'CI_POL', 'TEOL', 'LING', 'LIT', 'ARTES', 'OUTRA_SUB', name='subareacnpqenum', native_enum=False),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)
    op.alter_column('projects', 'area_secundaria',
               existing_type=sa.Enum('EXATAS', 'BIOLOGICAS', 'ENGENHARIAS', 'SAUDE', 'AGRARIAS', 'SOCIAIS_APLIC', 'HUMANAS', 'OUTRA', name='areacnpqenum', native_enum=False),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)
    op.alter_column('projects', 'subarea_primaria',
               existing_type=sa.Enum('MAT', 'PROB_EST', 'COMP', 'ASTRO', 'FIS', 'QUIM', 'GEO', 'OCEAN', 'BIO_GERAL', 'GENET', 'BOT_B', 'ZOO_B', 'ECOL', 'MORF', 'FISIOL', 'BIOQUIM', 'BIOFIS', 'FARMACOL', 'IMUNOL', 'MICROBIOL', 'PARASITOL', 'BIOL_MOL', 'ENG_CIV', 'ENG_MIN', 'ENG_MAT', 'ENG_ELE', 'ENG_MEC', 'ENG_QUIM', 'ENG_SAN', 'ENG_PROD', 'ENG_NUC', 'ENG_TRANSP', 'ENG_NAV', 'ENG_AERO', 'ENG_BIOMED', 'MED', 'ODONT', 'FARM', 'ENFERM', 'NUTRI', 'SAUDE_COL', 'FONOA', 'FISIOTER', 'ED_FIS', 'AGRON', 'REC_FLOR', 'ENG_AGRIC', 'ZOOTEC', 'MED_VET', 'REC_PESC', 'CI_ALIM', 'DIR', 'ADM_S', 'ECON_S', 'ARQ_URB', 'PLAN_URB', 'COMUN', 'CI_INF', 'MUSEOL', 'SERV_SOC', 'ECON_DOM', 'DES_IND', 'TURISMO', 'FILOS', 'SOCIOL', 'ANTROP', 'ARQUEOL', 'HIST', 'GEOGR', 'PSICOL', 'EDUC', 'CI_POL', 'TEOL', 'LING', 'LIT', 'ARTES', 'OUTRA_SUB', name='subareacnpqenum', native_enum=False),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)
    op.alter_column('projects', 'area_primaria',
               existing_type=sa.Enum('EXATAS', 'BIOLOGICAS', 'ENGENHARIAS', 'SAUDE', 'AGRARIAS', 'SOCIAIS_APLIC', 'HUMANAS', 'OUTRA', name='areacnpqenum', native_enum=False),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)
    op.alter_column('projects', 'departamento',
               existing_type=sa.Enum('FCTE', 'FGA', 'FACE', 'FACE_GPP', 'FACE_ADM', 'FACE_CCA', 'FACE_ECO', 'FACE_CIORD', 'FACE_CEIGES', 'FCTS', 'FCE', 'FAU', 'FAU_PRO', 'FAU_TEC', 'FAU_THAU', 'FAU_CPAB', 'FAV', 'FAC', 'FAC_DAP', 'FAC_JOR', 'FAC_COM', 'FCI', 'FD', 'FE', 'FE_MTC', 'FE_PGE', 'FE_TEF', 'FEF', 'FEF_CO', 'FUP', 'FM', 'FS', 'FS_FAR', 'FS_ODT', 'FS_DSC', 'FS_ENF', 'FS_NUT', 'FT', 'FT_EPR', 'FT_EFL', 'FT_ENC', 'FT_ENE', 'FT_ENM', 'FT_CEFTRU', 'IB', 'IB_BOT', 'IB_CEL', 'IB_CFS', 'IB_ECL', 'IB_FIT', 'IB_GEM', 'IB_ZOO', 'IB_CNANO', 'IB_CP', 'ICS', 'ICS_ELA', 'ICS_DAN', 'ICS_SOL', 'IDA', 'IDA_CEN', 'IDA_DIN', 'IDA_MUS', 'IDA_VIS', 'IE', 'IE_CIC', 'IE_EST', 'IE_MAT', 'IF', 'IF_CIF', 'IG', 'IG_SIS', 'ICH', 'ICH_FIL', 'ICH_GEA', 'ICH_HIS', 'ICH_SER', 'IL', 'IL_LET', 'IL_LIP', 'IL_TEL', 'IP', 'IP_PST', 'IP_PCL', 'IP_PED', 'IP_PPB', 'IP_CAEP', 'IPOL', 'IQ', 'IREL', name='departamentoenum', native_enum=False),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)
    op.alter_column('projects', 'status',
               existing_type=sa.Enum('rascunho', 'em_analise', 'submetido', 'aprovado', name='projectstatusenum', native_enum=False),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False,
               existing_server_default=sa.text("'rascunho'::character varying"))
    op.drop_table('questionnaire_responses')
    op.drop_table('questionnaire_jobs')
    # ### end Alembic commands ###
